# --------------- Starship Config ---------------

# Adiciona uma linha em branco para separar do comando anterior
add_newline = true

# Layout com conector curvado e braços longos em cima e em baixo
format = """
[╭─](fg:#434C5E)[](#2E3440)\
$os\
[](fg:#2E3440 bg:#3B4252)\
$directory\
[](fg:#3B4252 bg:#434C5E)\
$git_branch\
$git_status\
[](fg:#434C5E)\
\n[╰─](fg:#434C5E)$character"""

[os]
disabled = false
style = "bg:#2E3440 fg:#ECEFF4"

[os.symbols]
Arch = "󰣇 "
CachyOS = "󰣇 "
Linux = "󰣇 "

[directory]
# Branco puro para contraste profissional
style = "bg:#3B4252 fg:#FFFFFF"
truncation_length = 0
format = "[  $path ]($style)"

[git_branch]
symbol = " "
style = "bg:#434C5E fg:#B4D273"
format = "[[ $symbol$branch ]($style)]($style)"

[git_status]
style = "bg:#434C5E fg:#FABD2F"
format = "[[($all_status$ahead_behind )]($style)]($style)"
untracked = " ?$count "
modified = " !$count "
staged = " +$count "

[character]
# Espaço adicional para o cursor não colar na linha
success_symbol = " [❯](bold green)"
error_symbol = " [❯](bold red)"